package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1

/**
     * ItemReview generated by hbm2java
     * 
     * Represents a review for an item. It's mapping file is ItemReview.hbm.xml
     * 
     * @author Nick Dell'Osa
     * @version %PROJECT_VERSION%
 */
public class ItemReview extends Review<Item> implements java.io.Serializable {

    private Item item;
    /**
     * Empty constructor required by Hibernate
     */
    public ItemReview() {
    }
    /**
     * Returns the item in the review. Required by Hibernate
     * @return the item in the review.
     */
    public Item getItem() {
        return this.item;
    }
    /**
     * Sets the item in the review. Required by Hibernate
     * @param i the item in the review.
     */
    public void setItem(Item i) {
        this.item = i;
    }

    @Override
    public Item getReviewed() {
        return this.item;
    }

    @Override
    public void setReviewed(Item reviewed) {
        this.item = reviewed;
    }
    
}


