package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.TreeSet;
import org.hibernate.Hibernate;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Item generated by hbm2java
 * 
 * This class represents individual food items on a truck's menu(s). Its mapping file is Item.hbm.xml 
 * 
 * @author Nick Dell'Osa
 * @version %PROJECT_VERSION%
 */
public class Item implements java.io.Serializable, Reviewable, Taggable, Searchable, Modifiable {


     private int id;
     private String itemName;
     private double price;
     private Menu menu;
     private List<ItemReview> itemReviews;
     private Set<Tag> tags;

     /**
     * Required empty constructor.
     */
    public Item() {
    }

    /**
    Constructor required by Hibernate
    * @param itemName The name of this item
    * @param price The price of this item
    */
    public Item(String itemName, double price) {
        this.itemName = itemName;
        this.price = price;
    }
   
    /**
     * Returns this items ID. Required by Hibernate
     * @return the item's ID
     */
    public int getId() {
        return this.id;
    }
    /**
     * Sets an item's ID. Required by Hibernate
     * @param id The item's ID
     */
    public void setId(Integer id) {
        this.id = id;
    }
    /**
     * Returns the item's name. Required by Hibernate
     * @return the item's name
     */
    public String getItemName() {
        return this.itemName;
    }
    /**
     * Sets an item's name. Required by Hibernate
     * @param itemName the item's name
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    /**
     * Returns an item's price. Required by Hibernate
     * @return the price of an item
     */
    public double getPrice() {
        return this.price;
    }
    /**
     * Sets an item's price. Required by Hibernate
     * @param price the price of the item
     */
    public void setPrice(double price) {
        this.price = price;
    }
    /**
     * Returns the menu this item belongs to. Required by Hibernate
     * @return the menu this item belongs to
     */
    public Menu getMenu() {
        return menu;
    }
    /**
     * Sets the menu this item belongs to. Required by Hibernate
     * @param menu the menu this item belongs to
     */
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    /**
     * Returns a list of reviews of the item. Required by Hibernate
     * @return a list of the item's reviews.
     */
    public List getItemReviews() {
        return this.itemReviews;
    }
    /**
     * Adds a review to the item's list of reviews. 
     * @param r The review to be added to this item's list of reviews
     */
    @Override
    public void addReview(Review r) {
        r.setReviewed(this);
    }
    /**
     * Returns a set of tags associated with this item. Required by Hibernate
     * @return the set of tags associated with the item
     */
    @Override
    public Set<Tag> getTags() {
        return this.tags;
    }
    /**
     * Associates one or more tags with an item
     * @param t The tag(s) to be associated with the item
     */
    @Override
    public void addTags(Tag... t) {
        for (Tag x : t) {
            x.addEntity(this);
        }
    }
    /**
     * Sets the list of reviews for this item. Required by Hibernate
     * @param itemReviews the list of reviews for this item
     */
    public void setItemReviews(List<ItemReview> itemReviews) {
        this.itemReviews = itemReviews;
        this.removeNullReviews();
    }
    /**
     * Sets the set of tags associated with this item. Required by Hibernate
     * @param tags the set of tags associated with this item.
     */
    public void setTags(Set tags) {
        this.tags = tags;
    }

    @Override
    public String getSearchName() {
        return this.itemName;
    }
    /**
     * Retrieves a list of items that match the specified terms.
     * @param criteria the String to match
     * @return a list of items that match the specified terms
     */
    public static List<Item> searchItems(String criteria) {
        String terms = criteria.toLowerCase();
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(
                "from Item where itemName like '%" + terms + "%'"
        );
        List l = q.list();
        session.close();
        ArrayList<Item> results = new ArrayList<>(l.size());
        for (Searchable s : Searchable.SearchOrganizer.organize(l, terms)) results.add((Item)s);
        return results;
    }

    @Override
    public int getScore() {
        if (itemReviews == null || itemReviews.isEmpty())
            return 0;
        double score = 0.0;
        for (ItemReview ir : itemReviews) {
            score += (double)ir.getReviewStars();
        }
        score /= (double)itemReviews.size();
        return (int) Math.round(score);
    }

    @Override
    public Item loadReviews() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Item retval = (Item) session.get(Item.class, this.getId());
        Hibernate.initialize(retval.getItemReviews());
        session.getTransaction().commit();
        session.close();
        retval.getItemReviews().size();
        this.setItemReviews(retval.getItemReviews());
        return retval;
    }

    @Override
    public Item loadTags() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Item retval = (Item) session.get(Item.class, this.getId());
        Hibernate.initialize(retval.getTags());
        session.getTransaction().commit();
        session.close();
        retval.getTags().size();
        this.setTags(retval.getTags());
        return retval;
    }
    /**
     * Retrieves the item with the specified id.
     * @param id the id of the Item object to retrieve.
     * @param loadReviews true if you want to load reviews with this item object, false otherwise
     * @param loadTags true if you want to load tags with this item object, false otherwise
     * @return the item with the specified id
     */
    public static Item getItemByID(int id, boolean loadReviews, boolean loadTags) {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Query q = session.createQuery(
                "from Item where id=" + id
        );
        Item retval = (Item) q.uniqueResult();
        if (loadReviews) {
            Hibernate.initialize(retval.getItemReviews());
            retval.getItemReviews().size();
        }
        if (loadTags) {
            Hibernate.initialize(retval.getTags());
            for (Tag t : retval.getTags()) {
                Hibernate.initialize(t.getTrucks());
                Hibernate.initialize(t.getItems());
            }
        }
        session.close();
        return retval;
    }
    
    public static Item getItemByID(int id) {
        return Item.getItemByID(id, false, false);
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o instanceof Item) {
            Item i = (Item) o;
            return this.id == i.id;
        }
        return false;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 53 * hash + this.id;
        hash = 53 * hash + Objects.hashCode(this.itemName);
        hash = 53 * hash + (int) (Double.doubleToLongBits(this.price) ^ (Double.doubleToLongBits(this.price) >>> 32));
        return hash;
    }

    @Override
    public void removeNullReviews() {
        if (this.getItemReviews() != null) {
            for (int i=0; i < this.getItemReviews().size(); i++) {
                if (this.getItemReviews().get(i) == null) this.getItemReviews().remove(i);
            }
        }
    }

    @Override
    public void save() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.saveOrUpdate(this);
        session.getTransaction().commit();
        session.close();
    }

    @Override
    public void delete() {
        Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        Item item = (Item) session.get(Item.class, this.getId());
        Hibernate.initialize(item.getItemReviews());
        for (ItemReview ir : item.itemReviews) 
            session.delete(ir);
        
        session.delete(item);
        session.getTransaction().commit();
        session.close();
    }

}


