package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1

/**
 * ItemReview generated by hbm2java
 */
public class ItemReview extends Review<Item> implements java.io.Serializable {

    private int id;

    public ItemReview() {
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
}


