package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1


import java.util.Arrays;
import java.util.Set;

/**
 * Menu generated by hbm2java
 * @author Nick Dell'Osa
 * @version %PROJECT_VERSION%
 * 
 * Represents a truck's menu. Trucks can have one or more menus, each representing a category of food served by the truck. The menu serves as an organization unit. It's mapping file is Menu.hbm.xml. 
 */
public class Menu  implements java.io.Serializable {

     private int id;
     private Truck truck;
     private String menuName;
     private String description;
     private Set<Item> items;

     /**
      * Empty constructor required by Hibernate
      */
    public Menu() {
    }

    /**
     * Constructor required by Hibernate
     * @param menuName The name of this menu.
     */
    public Menu(String menuName) {
        this.menuName = menuName;
    }
    /**
     * Constructor required by Hibernate
     * @param truck The truck this menu belongs to.
     * @param menuName The name of this menu.
     * @param description A description of the contents of this menu.
     * @param items The set of items on this menu. 
     */
    public Menu(Truck truck, String menuName, String description, Set items) {
       this.truck = truck;
       this.menuName = menuName;
       this.description = description;
       this.items = items;
    }
    /**
     * Returns the ID of this menu. Required by Hibernate
     * @return the ID of this menu
     */
    public int getId() {
        return this.id;
    }
    /**
     * Sets the ID of this 
     * @param id the ID of this menu
     */
    public void setId(int id) {
        this.id = id;
    }
    /**
     * Returns the truck this menu belongs to. Required by Hibernate
     * @return the truck this menu belongs to
     */
    public Truck getTruck() {
        return this.truck;
    }
    /**
     * Sets the truck this menu belongs to. Required by Hibernate
     * @param truck the truck this menu belongs to
     */
    public void setTruck(Truck truck) {
        this.truck = truck;
    }
    /**
     * Returns the name of this menu. Required by Hibernate
     * @return the name of this menu
     */
    public String getMenuName() {
        return this.menuName;
    }
    /**
     * Sets the name of this menu. Required by Hibernate
     * @param menuName the name of this menu
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    /**
     * Returns a description of the contents of this menu. Required by Hibernate
     * @return a description of the contents of this menu
     */
    public String getDescription() {
        return this.description;
    }
    /**
     * Sets the description of the contents of this menu. Required by Hibernate
     * @param description the description of the contents of this menu
     */
    public void setDescription(String description) {
        this.description = description;
    }
    /**
     * Returns the set of items on this menu. Required by Hibernate
     * @return the set of items on this menu
     */
    public Set getItems() {
        return this.items;
    }
    /**
     * Sets the set of items on this menu. Required by Hibernate
     * @param items the set of items on this menu
     */
    public void setItems(Set items) {
        this.items = items;
    }
    /**
     * Adds one or more items to this menu.
     * @param item the item(s) to be added to this menu
     */
    public void addItems(Item... item) {
        items.addAll(Arrays.asList(item));
    }




}


