package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer id;
     private Truck truck;
     private String menuName;
     private String description;
     private Set items = new HashSet(0);

    public Menu() {
    }

	
    public Menu(String menuName) {
        this.menuName = menuName;
    }
    public Menu(Truck truck, String menuName, String description, Set items) {
       this.truck = truck;
       this.menuName = menuName;
       this.description = description;
       this.items = items;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Truck getTruck() {
        return this.truck;
    }
    
    public void setTruck(Truck truck) {
        this.truck = truck;
    }
    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


