package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TruckReview generated by hbm2java
 */
public class TruckReview extends Review<Truck> implements java.io.Serializable {

     private int id;

    public TruckReview() {
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public Truck getTruck() {
        return this.reviewed;
    }
    
    public void setTruck(Truck t) {
        this.reviewed = t;
    }
   
}


