package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1

import java.sql.Time;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

/**
 * Truck generated by hbm2java
 */
public class Truck implements java.io.Serializable, Reviewable, Taggable {

     private int id;
     private String truckName;
     private double latitude;
     private double longitude;
     private Time openingTime;
     private Time closingTime;
     private List<TruckReview> truckReviews;
     private List<Menu> menus;
     private Set<Tag> tags = new TreeSet();

    public Truck() {
        
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTruckName() {
        return this.truckName;
    }
    
    public void setTruckName(String truckName) {
        this.truckName = truckName;
    }
    public double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }
    public double getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }
    public List getTruckReviews() {
        return this.truckReviews;
    }

    public List getMenus() {
        return this.menus;
    }

    @Override
    public void addReview(Review r) {
        if (!r.getReviewed().equals(this)) {
            //error handling
            return;
        }
        truckReviews.add((TruckReview)r);
    }

    @Override
    public Set getTags() {
        return this.tags;
    }

    @Override
    public void addTags(Tag... t) {
        for (Tag x : t) {
            if (!x.getTrucks().contains(this)) x.addEntity(this);
            tags.add(x);
        }
    }
    
    public void setTruckReviews(List<TruckReview> truckReviews) {
        this.truckReviews = truckReviews;
    }

    public void setMenus(List<Menu> menus) {
        this.menus = menus;
    }

    public void setTags(Set<Tag> tags) {
        this.tags.addAll(tags);
    }

    public Time getOpeningTime() {
        return openingTime;
    }

    public void setOpeningTime(Time openingTime) {
        this.openingTime = openingTime;
    }

    public Time getClosingTime() {
        return closingTime;
    }

    public void setClosingTime(Time closingTime) {
        this.closingTime = closingTime;
    }

}


