package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1

/**
 * TruckReview generated by hbm2java
 * 
 * Represents a review for a truck. Its mapping file is TruckReview.hbm.xml
 * 
 * @author Nick Dell'Osa
 * @version %PROJECT_VERSION%
 */
public class TruckReview extends Review<Truck> implements java.io.Serializable {

    private Truck truck;
     /**
     * Empty constructor required by Hibernate
     */
    public TruckReview() {
    }
    /**
     * Returns the truck in the review. Required by Hibernate
     * @return the truck in the review.
     */
    public Truck getTruck() {
        return this.truck;
    }
    /**
     * Sets the truck in the review. Required by Hibernate
     * @param t the truck in the review
     */
    public void setTruck(Truck t) {
        this.truck = t;
    }

    @Override
    public Truck getReviewed() {
        return this.truck;
    }

    @Override
    public void setReviewed(Truck reviewed) {
        this.truck = reviewed;
    }
   
}


