package edu.temple.tutrucks;
// Generated Feb 15, 2016 6:30:46 PM by Hibernate Tools 4.3.1

import java.util.ArrayList;
import java.util.List;




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String userEmail;
     private String passWord;
     private boolean fbLink;
     private String avatar;
     private List<TruckReview> truckReviews = new ArrayList();
     private List<ItemReview> itemReviews = new ArrayList();

    public User() {
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getPassWord() {
        return this.passWord;
    }
    
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
    public boolean isFbLink() {
        return this.fbLink;
    }
    
    public void setFbLink(boolean fbLink) {
        this.fbLink = fbLink;
    }
    public String getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
    
    public List getTruckReviews() {
        return this.truckReviews;
    }
    
    public void addReview(Review r) {
        if (!r.getUser().equals(this)) {
            //error handling
            return;
        }
        if (r.getClass() == TruckReview.class)
            truckReviews.add((TruckReview)r);
        else
            itemReviews.add((ItemReview)r);
    }




}


